version: '3.5'

services:   

  fetcher:
    build: 
      context: fetcher/
    container_name: fetcher
    restart: always
    environment:
      - USER=${USER:-admin}
      - PASSWORD=${PASSWORD:-secret} 
      - SQLSERVER_SAGRES19_HOST=${SQLSERVER_SAGRES19_HOST:-host}
      - SQLSERVER_SAGRES19_Database=${SQLSERVER_SAGRES19_Database:-db}
      - SQLSERVER_SAGRES19_PORT=${SQLSERVER_SAGRES19_PORT:-1401}
      - SQLSERVER_SAGRES19_USER=${SQLSERVER_SAGRES19_USER:-user}
      - SQLSERVER_SAGRES19_PASS=${SQLSERVER_SAGRES19_PASS:-secret}
    volumes:
      - ./fetcher:/app/fetcher
    ports:
      - 8787:8787
    networks:
      - proxynet

  transformer:
    build: 
      context: transformador/
    container_name: transformador
    restart: always
    environment:
      - USER=${USER:-admin}
      - PASSWORD=${PASSWORD:-secret} 
    volumes:
      - ./transformador:/app/transformador
      - ./fetcher/data:/app/fetcher/data
    networks:
      - proxynet

networks:
  proxynet:
    name: monitor_cidadao_network
